// Generated by SolidPython 1.1.3 on 2022-07-14 17:17:28


translate(v = [9.0000000000, 4.5000000000, 0]) {
	union() {
		translate(v = [0, 0]) {
			rotate(a = 0) {
				union() {
					union() {
						translate(v = [4.5000000000, 0]) {
							circle($fn = 64, r = 3.4700000000);
						}
						translate(v = [-4.5000000000, 0]) {
							circle($fn = 64, r = 3.4700000000);
						}
					}
					union() {
						translate(v = [1.5450000000, 0]) {
							square(center = true, size = [1.0300000000, 3.4500000000]);
						}
						translate(v = [-1.5450000000, 0]) {
							square(center = true, size = [1.0300000000, 3.4500000000]);
						}
					}
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
base_path="./designs/open_chamber/2compartment/"
well_gap=4.5
well_rad=6.94/2.0
chan_l=(well_gap-well_rad)*2.0
chan_gap=0.01
chan_w=0.01
num_chans=int(well_rad/(chan_gap+chan_w))
num_connected_wells=4
add_wells=True
add_chambers=True
add_channels=True
#dimensions of each cut-out device
dims = [9*2, 9, 0]
#number of devices
grid_size = [6,8]
units_from_center=(1,0)

#make bottom layer
base_name="2compartment_single_device_bottom"
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
                                        add_chambers=add_chambers,alignment=None)
#open_chamber=solid.translate([9,4.5,0])(open_chamber)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(open_chamber,osp.join(dxf_path))
to_dxf(dxf_path)
#make array of all the individual pairs of devices
base_name="2compartment_multi_device_bottom"
device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = True,units_from_center=units_from_center)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)

#make top layer
add_channels=False
base_name="2compartment_single_device_top"
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
                                        add_chambers=add_chambers,alignment=None)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(open_chamber,osp.join(dxf_path))
to_dxf(dxf_path)
#make array of all the individual pairs of devices
base_name="2compartment_multi_device_top"
device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = "hollow",units_from_center=units_from_center)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)

##dimensions of each cut-out device
#dims = [9*2, 9, 0]
##number of devices
#grid_size = [6,8]
##height of 3d printed walls
#wall_height=10
##thickness of 3d printed walls
#wall_thickness=2
##diameter of wafer in mm
#wafer_size=101.4
#base_name="2compartment_multi_device"
#
##make array of all the individual pairs of devices
#device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = None)
##translate back since unit array is already translated by the offset in the make_open_chamber functions call
#device_array = solid.translate([-6,-5,0])(device_array)
#
#devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
#solid.scad_render_to_file(device_array,devices_dxf_path)
#to_dxf(devices_dxf_path)
 
 
************************************************/
