// Generated by SolidPython 1.1.3 on 2022-06-22 19:07:15


rotate(a = [0, 0, 45]) {
	union() {
		square(center = true, size = [2.2900000000, 2.2900000000]);
		union() {
			translate(v = [0.0000000000, 0.0000000000]) {
				union() {
					translate(v = [0, 0]) {
						rotate(a = 0) {
							union() {
								union() {
									translate(v = [6.3600000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
									translate(v = [-6.3600000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
								}
								union() {
									translate(v = [0, 0.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [5.7240000000, 0.0100000000]);
										}
									}
								}
								union() {
									translate(v = [4.6110000000, 0]) {
										square(center = true, size = [3.4980000000, 2.2900000000]);
									}
									translate(v = [-4.6110000000, 0]) {
										square(center = true, size = [3.4980000000, 2.2900000000]);
									}
								}
							}
						}
					}
				}
			}
			rotate(a = [0, 0, 90]) {
				translate(v = [0.0000000000, 0.0000000000]) {
					union() {
						translate(v = [0, 0]) {
							rotate(a = 0) {
								union() {
									union() {
										translate(v = [6.3600000000, 0]) {
											circle($fn = 64, r = 3.4700000000);
										}
										translate(v = [-6.3600000000, 0]) {
											circle($fn = 64, r = 3.4700000000);
										}
									}
									union() {
										translate(v = [0, 0.0000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.0200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.0200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.0400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.0400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.0600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.0600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.0800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.0800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.1000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.1000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.1200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.1200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.1400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.1400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.1600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.1600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.1800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.1800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.2000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.2000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.2200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.2200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.2400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.2400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.2600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.2600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.2800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.2800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.3000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.3000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.3200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.3200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.3400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.3400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.3600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.3600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.3800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.3800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.4000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.4000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.4200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.4200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.4400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.4400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.4600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.4600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.4800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.4800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.5000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.5000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.5200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.5200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.5400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.5400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.5600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.5600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.5800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.5800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.6000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.6000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.6200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.6200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.6400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.6400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.6600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.6600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.6800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.6800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.7000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.7000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.7200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.7200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.7400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.7400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.7600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.7600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.7800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.7800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.8000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.8000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.8200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.8200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.8400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.8400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.8600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.8600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.8800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.8800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.9000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.9000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.9200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.9200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.9400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.9400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.9600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.9600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 0.9800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -0.9800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.0000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.0000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.0200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.0200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.0400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.0400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.0600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.0600000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.0800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.0800000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.1000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.1000000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.1200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.1200000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, 1.1400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
										translate(v = [0, -1.1400000000]) {
											translate(v = [0, 0]) {
												square(center = true, size = [5.7240000000, 0.0100000000]);
											}
										}
									}
									union() {
										translate(v = [4.6110000000, 0]) {
											square(center = true, size = [3.4980000000, 2.2900000000]);
										}
										translate(v = [-4.6110000000, 0]) {
											square(center = true, size = [3.4980000000, 2.2900000000]);
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
base_path="./designs/open_chamber/gradient_layout/"
base_name="closed_gradient_single_device"
well_gap=6.36
well_rad=6.94/2.0
chan_l=well_gap
chan_gap=0.01
chan_w=0.01
num_chans=int((well_rad/1.5)/(chan_gap+chan_w))
oligo_channel_width=0.1
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l*0.9,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=0,casing_y=0,chamber_len_until=chan_l,
                                        rotate_units=0,alignment=None)

open_chamber2=solid.rotate([0,0,90])(open_chamber)
connected_chambers=solid.union()(open_chamber,open_chamber2)
width_all_channels=num_chans*chan_w+(num_chans-1)*chan_gap
common_area = solid.square([width_all_channels,width_all_channels],center=True)()
connected_chambers = solid.union()(common_area,connected_chambers)

connected_chambers=solid.rotate([0,0,45])(connected_chambers)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(connected_chambers,osp.join(dxf_path))
to_dxf(dxf_path)


##dimensions of each cut-out device
dims = [9*2, 9*2, 0]
##number of devices
grid_size = [6,4]
base_name="closed_gradient_multi_device"
##make array of all the individual pairs of devices
device_array = make_unit_array(connected_chambers,dims,grid_size, dxf=True, alignment = None)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)
 
 
************************************************/
