// Generated by SolidPython 1.1.3 on 2022-06-22 16:57:02


union() {
	union() {
		translate(v = [0, 40.5000000000, 5.0000000000]) {
			cube(center = true, size = [2, 54, 10]);
		}
		translate(v = [40.5000000000, 0, 5.0000000000]) {
			cube(center = true, size = [81, 2, 10]);
		}
		translate(v = [0, 27]) {
			translate(v = [40.5000000000, 0, 5.0000000000]) {
				cube(center = true, size = [81, 2, 10]);
			}
		}
		translate(v = [0, 54]) {
			translate(v = [40.5000000000, 0, 5.0000000000]) {
				cube(center = true, size = [81, 2, 10]);
			}
		}
		translate(v = [0, 81]) {
			translate(v = [40.5000000000, 0, 5.0000000000]) {
				cube(center = true, size = [81, 2, 10]);
			}
		}
		translate(v = [27, 0]) {
			translate(v = [0, 40.5000000000, 5.0000000000]) {
				cube(center = true, size = [2, 54, 10]);
			}
		}
		translate(v = [54, 0]) {
			translate(v = [0, 40.5000000000, 5.0000000000]) {
				cube(center = true, size = [2, 54, 10]);
			}
		}
	}
	translate(v = [40.5000000000, 27.0000000000]) {
		difference() {
			cylinder($fn = 256, h = 10, r = 50.7000000000);
			cylinder($fn = 256, h = 10, r = 48.7000000000);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
base_path="./designs/open_chamber/gradient_layout/"
base_name="gradient_single_device"
well_gap=4.5
well_rad=6.94/2.0
chan_l=(well_gap-well_rad)*2.0
chan_gap=0.01
chan_w=0.01
num_chans=int(well_rad/(chan_gap+chan_w))
num_connected_wells=4
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=0,casing_y=0,chamber_len_until=chan_l,
                                        rotate_units=0,alignment=None)
open_chamber=solid.translate([well_gap,0,0])(open_chamber)
connected_chambers = []
num_connected_wells=float(num_connected_wells)
for i in range(int(num_connected_wells)):
    connected_chambers.append(solid.rotate([0,0,(360.0/num_connected_wells)*i])(open_chamber))
connected_chambers = solid.union()(*connected_chambers)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(connected_chambers,osp.join(dxf_path))
to_dxf(dxf_path)


#dimensions of each cut-out device
dims = [9*3, 9*3, 0]
#number of devices
grid_size = [2,3]
#height of 3d printed walls
wall_height=10
#thickness of 3d printed walls
wall_thickness=2
#diameter of wafer in mm
wafer_size=101.4
base_name="gradient_multi_device"

#make array of all the individual pairs of devices
device_array = make_unit_array(connected_chambers,dims,grid_size, dxf=True, alignment = None)
#translate back since unit array is already translated by the offset in the make_open_chamber functions call
device_array = solid.translate([-6,-5,0])(device_array)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)

wall = make_walls(wafer_size,wall_thickness,grid_size,dims,height=wall_height,segments=256)
wall_2d = solid.projection()(wall)
wall_path=osp.join(base_path,"wall_"+base_name+".scad")
solid.scad_render_to_file(wall,wall_path)
r.render(wall, outfile=wall_path.replace("scad","stl"))

wall_and_devices = solid.union()(wall_2d,device_array)
wall_and_devices_path=osp.join(base_path,"wall_and_devices_"+base_name+".scad")
solid.scad_render_to_file(wall_and_devices,wall_and_devices_path)
to_dxf(wall_and_devices_path)

 
 
************************************************/
