// Generated by SolidPython 1.1.3 on 2022-07-14 17:45:23


union() {
	translate(v = [0, 0]) {
		translate(v = [6.0000000000, 2.5000000000, 0]) {
			rotate(a = 0) {
				union() {
					union() {
						translate(v = [0, 0.0000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.9000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
					}
					union() {
						translate(v = [2, 0]) {
							circle($fn = 64, r = 2.5000000000);
						}
						translate(v = [-2, 0]) {
							circle($fn = 64, r = 2.5000000000);
						}
					}
					union() {
						translate(v = [0.7500000000, 0]) {
							square(center = true, size = [0.5000000000, 1.7800000000]);
						}
						translate(v = [-0.7500000000, 0]) {
							square(center = true, size = [0.5000000000, 1.7800000000]);
						}
					}
				}
			}
		}
	}
	translate(v = [0, 5]) {
		translate(v = [6.0000000000, 2.5000000000, 0]) {
			rotate(a = 0) {
				union() {
					union() {
						translate(v = [0, 0.0000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.0900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.0900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.1800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.1800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.2700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.2700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.3900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.3900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.4800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.4800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.5700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.5700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6300000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6600000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.6900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.6900000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7200000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7500000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.7800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.7800000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8100000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8400000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.8700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, -0.8700000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
						translate(v = [0, 0.9000000000]) {
							translate(v = [0, -0.0150000000]) {
								square(center = true, size = [1, 0.0100000000]);
							}
						}
					}
					union() {
						translate(v = [2, 0]) {
							circle($fn = 64, r = 2.5000000000);
						}
						translate(v = [-2, 0]) {
							circle($fn = 64, r = 2.5000000000);
						}
					}
					union() {
						translate(v = [0.7500000000, 0]) {
							square(center = true, size = [0.5000000000, 1.7800000000]);
						}
						translate(v = [-0.7500000000, 0]) {
							square(center = true, size = [0.5000000000, 1.7800000000]);
						}
					}
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
base_path="./designs/open_chamber/2compartment/"
well_gap=4.5
well_rad=6.94/2.0
chan_l=(well_gap-well_rad)*2.0
chan_gap=0.03
chan_w=0.01
num_chans=int(well_rad/(chan_gap+chan_w))
num_connected_wells=4
add_wells=True
add_chambers=True
add_channels=True
#dimensions of each cut-out device
dims = [9*2, 9, 0]
#number of devices
grid_size = [6,8]
units_from_center=(1,1)

def save_model(model,base_path,base_name):
    dxf_path=osp.join(base_path,base_name+".scad")
    solid.scad_render_to_file(model,osp.join(dxf_path))
    to_dxf(dxf_path)

"""
MAKE SINGLE DEVICE
"""
#make bottom layer
(single_chamber_wells,_),_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
                                        add_chambers=add_chambers,alignment=None)
save_model(open_chamber,base_path,"2compartment_single_device_bottom")
save_model(single_chamber_wells,base_path,"2compartment_single_device_top")

#"""
#MAKE 96WELL DEVICE
#"""
#
#(chamber_wells_multi,_),_,(open_chamber_multi,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
#                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
#                                        rows=grid_size[0],columns=grid_size[1],casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
#                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
#                                        add_chambers=add_chambers,alignment=True,units_from_center=units_from_center)
#
#save_model(open_chamber_multi,base_path,"2compartment_multi_device_bottom")
#save_model(chamber_wells_multi,base_path,"2compartment_multi_device_top")

"""
MAKE SINGLE DEVICE GRID
"""
well_rad=2.5
dims = [14, 14, 0]
#number of devices
grid_size = [5,5]
#height of 3d printed walls
wall_height=10
#thickness of 3d printed walls
wall_thickness=2
#diameter of wafer in mm
wafer_size=101.4
base_path="./designs/open_chamber/3mm_pairs_5x5"
base_name="3mm_pairs_5x5"
#_,_,(open_chamber,_)
(chamber_wells_many_single,_),_,(open_chamber_many_single,_)=make_open_chamber(wells_pos=wells_pos_from_center_2(2),
                                        well_rad=well_rad,chan_l=1,chan_w=0.01,chan_gap=0.02,num_chans=60,
                                        rows=1,columns=2,casing_x=12,casing_y=5,chamber_len_until=1,
                                        rotate_units=0,alignment=None)
#= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
#                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
#                                        rows=grid_size[0],columns=grid_size[1],casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
#                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
#                                        add_chambers=add_chambers,alignment=True,units_from_center=units_from_center)

save_model(open_chamber_many_single,base_path,"2compartment_many_single_device_bottom")
save_model(chamber_wells_many_single,base_path,"2compartment_many_single_device_top")

##make array of all the individual pairs of devices
#base_name="2compartment_multi_device_bottom"
#device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = True,units_from_center=units_from_center)
#devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
#solid.scad_render_to_file(device_array,devices_dxf_path)
#to_dxf(devices_dxf_path)
#
##make top layer
#add_channels=False
#base_name="2compartment_single_device_top"
#_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
#                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
#                                        rows=1,columns=1,casing_x=dims[0],casing_y=dims[1],chamber_len_until=chan_l,
#                                        rotate_units=0,add_channels=add_channels,add_wells=add_wells,
#                                        add_chambers=add_chambers,alignment=None)
#dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
#solid.scad_render_to_file(open_chamber,osp.join(dxf_path))
#to_dxf(dxf_path)
##make array of all the individual pairs of devices
#base_name="2compartment_multi_device_top"
#device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = "hollow",units_from_center=units_from_center)
#devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
#solid.scad_render_to_file(device_array,devices_dxf_path)
#to_dxf(devices_dxf_path)
#
###dimensions of each cut-out device
##dims = [9*2, 9, 0]
###number of devices
##grid_size = [6,8]
###height of 3d printed walls
##wall_height=10
###thickness of 3d printed walls
##wall_thickness=2
###diameter of wafer in mm
##wafer_size=101.4
##base_name="2compartment_multi_device"
##
###make array of all the individual pairs of devices
##device_array = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = None)
###translate back since unit array is already translated by the offset in the make_open_chamber functions call
##device_array = solid.translate([-6,-5,0])(device_array)
##
##devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
##solid.scad_render_to_file(device_array,devices_dxf_path)
##to_dxf(devices_dxf_path)
 
 
************************************************/
