// Generated by SolidPython 1.1.3 on 2022-07-13 20:12:50


union() {
	rotate(a = [0, 0, 0.0000000000]) {
		translate(v = [4.5000000000, 0, 0]) {
			translate(v = [0.0000000000, 0.0000000000]) {
				union() {
					translate(v = [0, 0]) {
						rotate(a = 0) {
							union() {
								union() {
									translate(v = [0, 0.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
								}
								union() {
									translate(v = [4.5000000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
									translate(v = [-4.5000000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
								}
								union() {
									translate(v = [1.5450000000, 0]) {
										square(center = true, size = [1.0300000000, 3.4500000000]);
									}
									translate(v = [-1.5450000000, 0]) {
										square(center = true, size = [1.0300000000, 3.4500000000]);
									}
								}
							}
						}
					}
				}
			}
		}
	}
	rotate(a = [0, 0, 180.0000000000]) {
		translate(v = [4.5000000000, 0, 0]) {
			translate(v = [0.0000000000, 0.0000000000]) {
				union() {
					translate(v = [0, 0]) {
						rotate(a = 0) {
							union() {
								union() {
									translate(v = [0, 0.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.7800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.8800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -0.9800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.0800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.1800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.2800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.3800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.4800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.5800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6400000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6600000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.6800000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.7000000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, 1.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
									translate(v = [0, -1.7200000000]) {
										translate(v = [0, 0]) {
											square(center = true, size = [2.0600000000, 0.0100000000]);
										}
									}
								}
								union() {
									translate(v = [4.5000000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
									translate(v = [-4.5000000000, 0]) {
										circle($fn = 64, r = 3.4700000000);
									}
								}
								union() {
									translate(v = [1.5450000000, 0]) {
										square(center = true, size = [1.0300000000, 3.4500000000]);
									}
									translate(v = [-1.5450000000, 0]) {
										square(center = true, size = [1.0300000000, 3.4500000000]);
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
base_path="./designs/open_chamber/3compartment/"
base_name="3compartment_single_device"
well_gap=4.5
well_rad=6.94/2.0
chan_l=(well_gap-well_rad)*2.0
chan_gap=0.01
chan_w=0.01
num_chans=int(well_rad/(chan_gap+chan_w))
num_connected_wells=2
add_wells=True
add_chambers=True
add_channels=True
#dimensions of each cut-out device
dims = [9*3, 9, 0]
#number of devices
grid_size = [4,8]

#make bottom layer
base_name="3compartment_single_device_bottom"
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=0,casing_y=0,chamber_len_until=chan_l,
                                        rotate_units=0,alignment=None,add_channels=add_channels,add_wells=add_wells,
                                        add_chambers=add_chambers)
open_chamber=solid.translate([well_gap,0,0])(open_chamber)
connected_chambers = []
num_connected_wells=float(num_connected_wells)
for i in range(int(num_connected_wells)):
    connected_chambers.append(solid.rotate([0,0,(360.0/num_connected_wells)*i])(open_chamber))
connected_chambers = solid.union()(*connected_chambers)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(connected_chambers,osp.join(dxf_path))
to_dxf(dxf_path)
#make array of all the individual pairs of devices
base_name="3compartment_multi_device_bottom"
device_array = make_unit_array(connected_chambers,dims,grid_size, dxf=True, alignment = None)
#translate back since unit array is already translated by the offset in the make_open_chamber functions call
device_array = solid.translate([-6,-5,0])(device_array)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)

#make top layer
add_channels=False
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(well_gap),
                                        well_rad=well_rad,chan_l=chan_l,chan_w=chan_w,chan_gap=chan_gap,num_chans=num_chans,
                                        rows=1,columns=1,casing_x=0,casing_y=0,chamber_len_until=chan_l,
                                        rotate_units=0,alignment=None,add_channels=add_channels,add_wells=add_wells,
                                        add_chambers=add_chambers)
base_name="3compartment_single_device_top"
open_chamber=solid.translate([well_gap,0,0])(open_chamber)
connected_chambers = []
num_connected_wells=float(num_connected_wells)
for i in range(int(num_connected_wells)):
    connected_chambers.append(solid.rotate([0,0,(360.0/num_connected_wells)*i])(open_chamber))
connected_chambers = solid.union()(*connected_chambers)
dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(connected_chambers,osp.join(dxf_path))
to_dxf(dxf_path)
#make array of all the individual pairs of devices
base_name="3compartment_multi_device_top"
device_array = make_unit_array(connected_chambers,dims,grid_size, dxf=True, alignment = None)
#translate back since unit array is already translated by the offset in the make_open_chamber functions call
device_array = solid.translate([-6,-5,0])(device_array)
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)


#dimensions of each cut-out device
dims = [9*3, 9, 0]
#number of devices
grid_size = [4,8]
#height of 3d printed walls
#wall_height=10
#thickness of 3d printed walls
#wall_thickness=2
#diameter of wafer in mm
#wafer_size=101.4
base_name="3compartment_multi_device_top"


#adjacent_devices=[]
#adjacent_devices.append(device_array)
#adjacent_devices.append(solid.translate([9*1,9*2,0])(device_array))
#adjacent_devices.append(solid.translate([9*3,9*1,0])(device_array))
#adjacent_devices.append(solid.translate([9*2,-9*1,0])(device_array))
#adjacent_devices=solid.union()(*adjacent_devices)
#end_device=[]
#end_device.append(adjacent_devices)
#end_device.append(solid.translate([9*5,0,0])(adjacent_devices))
##end_device.append(solid.translate([9*5-2,-9,0])(connected_chambers))
#end_device=solid.union()(*end_device)
#adjacent_devices=end_device
#device_array=adjacent_devices
#
#
#
devices_dxf_path=osp.join(base_path,"devices_"+base_name+".scad")
solid.scad_render_to_file(device_array,devices_dxf_path)
to_dxf(devices_dxf_path)
#
#wall = make_walls(wafer_size,wall_thickness,grid_size,dims,height=wall_height,segments=256)
#wall_2d = solid.projection()(wall)
#wall_path=osp.join(base_path,"wall_"+base_name+".scad")
#solid.scad_render_to_file(wall,wall_path)
#r.render(wall, outfile=wall_path.replace("scad","stl"))
#
#wall_and_devices = solid.union()(wall_2d,device_array)
#wall_and_devices_path=osp.join(base_path,"wall_and_devices_"+base_name+".scad")
#solid.scad_render_to_file(wall_and_devices,wall_and_devices_path)
#to_dxf(wall_and_devices_path)

 
 
************************************************/
