// Generated by SolidPython 1.1.3 on 2022-06-06 16:40:58


union() {
	union() {
		translate(v = [0, 35.0000000000, 5.0000000000]) {
			cube(center = true, size = [2, 70, 10]);
		}
		translate(v = [35.0000000000, 0, 5.0000000000]) {
			cube(center = true, size = [70, 2, 10]);
		}
		translate(v = [0, 14]) {
			translate(v = [35.0000000000, 0, 5.0000000000]) {
				cube(center = true, size = [70, 2, 10]);
			}
		}
		translate(v = [0, 28]) {
			translate(v = [35.0000000000, 0, 5.0000000000]) {
				cube(center = true, size = [70, 2, 10]);
			}
		}
		translate(v = [0, 42]) {
			translate(v = [35.0000000000, 0, 5.0000000000]) {
				cube(center = true, size = [70, 2, 10]);
			}
		}
		translate(v = [0, 56]) {
			translate(v = [35.0000000000, 0, 5.0000000000]) {
				cube(center = true, size = [70, 2, 10]);
			}
		}
		translate(v = [0, 70]) {
			translate(v = [35.0000000000, 0, 5.0000000000]) {
				cube(center = true, size = [70, 2, 10]);
			}
		}
		translate(v = [14, 0]) {
			translate(v = [0, 35.0000000000, 5.0000000000]) {
				cube(center = true, size = [2, 70, 10]);
			}
		}
		translate(v = [28, 0]) {
			translate(v = [0, 35.0000000000, 5.0000000000]) {
				cube(center = true, size = [2, 70, 10]);
			}
		}
		translate(v = [42, 0]) {
			translate(v = [0, 35.0000000000, 5.0000000000]) {
				cube(center = true, size = [2, 70, 10]);
			}
		}
		translate(v = [56, 0]) {
			translate(v = [0, 35.0000000000, 5.0000000000]) {
				cube(center = true, size = [2, 70, 10]);
			}
		}
		translate(v = [70, 0]) {
			translate(v = [0, 35.0000000000, 5.0000000000]) {
				cube(center = true, size = [2, 70, 10]);
			}
		}
	}
	translate(v = [35.0000000000, 35.0000000000]) {
		difference() {
			cylinder($fn = 256, h = 10, r = 50.7000000000);
			cylinder($fn = 256, h = 10, r = 48.7000000000);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from make_device import *
#pair of device for 12 well plate
#make pair of device to fit in one 12 well plate well
_,_,(open_chamber,_)= make_open_chamber(wells_pos=wells_pos_from_center_2(2),
                                        well_rad=1.5,chan_l=1,chan_w=0.01,chan_gap=0.02,num_chans=60,
                                        rows=1,columns=2,casing_x=12,casing_y=5,chamber_len_until=1,
                                        rotate_units=0,alignment=None)
#dimensions of each cut-out device
dims = [14, 14, 0]
#number of devices
grid_size = [5,5]

#make array of all the individual pairs of devices
open_chamber_5x5_duplicates = make_unit_array(open_chamber,dims,grid_size, dxf=True, alignment = None)
#translate back since unit array is already translated by the offset in the make_open_chamber functions call
open_chamber_5x5_duplicates = solid.translate([-6,-5,0])(open_chamber_5x5_duplicates)
file_path="./designs/open_chamber/device_3mm_5x5_duplicates.scad"
solid.scad_render_to_file(open_chamber_5x5_duplicates,file_path)
to_dxf(file_path)

wall_height=10
wall_thickness=2
wafer_size=101.4
wall = make_walls(wafer_size,wall_thickness,grid_size,dims,height=wall_height,segments=256)
wall_2d = solid.projection()(wall)
file_path="./designs/open_chamber/wall_device_3mm_5x5_duplicates.scad"
solid.scad_render_to_file(wall,file_path)
r.render(wall, outfile=file_path.replace("scad","stl"))

wall_devices = solid.union()(wall_2d,open_chamber_5x5_duplicates)
file_path="./designs/open_chamber/wall_and_device_3mm_5x5_duplicates.scad"
solid.scad_render_to_file(wall_devices,file_path)
to_dxf(file_path)
 
 
************************************************/
