// Generated by SolidPython 0.4.8 on 2020-09-19 22:13:57


difference() {
	translate(v = [-0.0500000000, -0.0500000000, 0]) {
		square(size = [9.1000000000, 9.1000000000]);
	}
	difference() {
		translate(v = [4.5000000000, 4.5000000000]) {
			union() {
				translate(v = [0.0000000000, 0.0000000000]) {
					difference() {
						translate(v = [0, 0]) {
							square(center = true, size = [9.0000000000, 9.0000000000]);
						}
						union() {
							union() {
								translate(v = [0, 0.0000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.2500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.2500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.3000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.3000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.3500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.3500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.4000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.4000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.4500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.4500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.5000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.5000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.5500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.5500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.6000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.6000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.6500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.6500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.7000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.7000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.7500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.7500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.8000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.8000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.8500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.8500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.9000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.9000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 0.9500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -0.9500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.0000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.0000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.2500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.2500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.3000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.3000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.3500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.3500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.4000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.4000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.4500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.4500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.5000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.5000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.5500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.5500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.6000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.6000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.6500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.6500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.7000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.7000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.7500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.7500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.8000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.8000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.8500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.8500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.9000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.9000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 1.9500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -1.9500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 2.0000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -2.0000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 2.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -2.0500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 2.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -2.1000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 2.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -2.1500000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, 2.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
								translate(v = [0, -2.2000000000]) {
									translate(v = [0, 0]) {
										square(center = true, size = [0.8000000000, 0.0100000000]);
									}
								}
							}
							union() {
								translate(v = [-2.2500000000, 2.2500000000]) {
									circle($fn = 64, r = 1.5000000000);
								}
								translate(v = [2.2500000000, 2.2500000000]) {
									circle($fn = 64, r = 1.5000000000);
								}
								translate(v = [-2.2500000000, -2.2500000000]) {
									circle($fn = 64, r = 1.5000000000);
								}
								translate(v = [2.2500000000, -2.2500000000]) {
									circle($fn = 64, r = 1.5000000000);
								}
							}
							union() {
								translate(v = [1.3250000000, 0]) {
									square(center = true, size = [1.8500000000, 4.4100000000]);
								}
								translate(v = [-1.3250000000, 0]) {
									square(center = true, size = [1.8500000000, 4.4100000000]);
								}
							}
						}
					}
				}
			}
		}
		union() {
			translate(v = [31.5000000000, 18.0000000000, 0]) {
				difference() {
					union() {
						translate(v = [0.1406250000, 0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.1406250000, -0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
					}
					union() {
						translate(v = [0.0703125000, 0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.0703125000, -0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
					}
				}
			}
			translate(v = [-22.5000000000, 18.0000000000, 0]) {
				difference() {
					union() {
						translate(v = [0.1406250000, 0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.1406250000, -0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
					}
					union() {
						translate(v = [0.0703125000, 0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.0703125000, -0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
					}
				}
			}
			translate(v = [31.5000000000, -9.0000000000, 0]) {
				difference() {
					union() {
						translate(v = [0.1406250000, 0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.1406250000, -0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
					}
					union() {
						translate(v = [0.0703125000, 0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.0703125000, -0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
					}
				}
			}
			translate(v = [-22.5000000000, -9.0000000000, 0]) {
				difference() {
					union() {
						translate(v = [0.1406250000, 0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.1406250000, -0.1406250000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.2812500000]);
										square(center = false, size = [0.2812500000, 1.1250000000]);
									}
								}
							}
						}
					}
					union() {
						translate(v = [0.0703125000, 0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 180) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
						translate(v = [-0.0703125000, -0.0703125000, 0]) {
							translate(v = [0, 0, 0]) {
								rotate(a = 0) {
									union() {
										square(center = false, size = [1.1250000000, 0.1406250000]);
										square(center = false, size = [0.1406250000, 1.1250000000]);
									}
								}
							}
						}
					}
				}
			}
		}
	}
}