// Generated by SolidPython 1.1.3 on 2024-01-09 10:56:56


union() {
	difference() {
		difference() {
			difference() {
				union() {
					translate(v = [0, 0, 4.2500000000]) {
						cube(center = true, size = [127.5000000000, 85.3500000000, 8.5000000000]);
					}
					translate(v = [0, 0, 12.7500000000]) {
						cube(center = true, size = [125.5000000000, 83.3500000000, 8.5000000000]);
					}
				}
				translate(v = [0, 0, 0.5000000000]) {
					cube(center = true, size = [125.5000000000, 83.3500000000, 1]);
				}
			}
			union() {
				translate(v = [-62.7500000000, 41.6750000000, 8.5000000000]) {
					translate(v = [0, -10, 0]) {
						linear_extrude(height = 8.5000000000) {
							polygon(points = [[0, 0], [0, 10], [0, 10], [0, 10], [10, 10], [10, 10]]);
						}
					}
				}
				translate(v = [-62.7500000000, -41.6750000000, 8.5000000000]) {
					translate(v = [10, 0, 0]) {
						rotate(a = 90) {
							linear_extrude(height = 8.5000000000) {
								polygon(points = [[0, 0], [0, 10], [0, 10], [0, 10], [10, 10], [10, 10]]);
							}
						}
					}
				}
			}
		}
		translate(v = [-52.0000000000, -39.0000000000, 0]) {
			translate(v = [13.0000000000, 13.0000000000, 0]) {
				union() {
					translate(v = [0, 0, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [26, 0, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [52, 0, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [78, 0, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [0, 26, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [26, 26, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [52, 26, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [78, 26, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [0, 52, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [26, 52, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [52, 52, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
					translate(v = [78, 52, 0.0000000000]) {
						translate(v = [0, 0, 8.5000000000]) {
							cylinder($fn = 64, center = true, h = 17.0000000000, r = 11.4500000000);
						}
					}
				}
			}
		}
	}
	translate(v = [-52.0000000000, -39.0000000000, 0]) {
		translate(v = [13.0000000000, 13.0000000000, 0]) {
			union() {
				translate(v = [0, 0, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [26, 0, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [52, 0, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [78, 0, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [0, 26, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [26, 26, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [52, 26, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [78, 26, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [0, 52, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [26, 52, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [52, 52, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
				translate(v = [78, 52, 0.0000000000]) {
					union() {
						difference() {
							translate(v = [0, 0, 8.5000000000]) {
								difference() {
									cylinder($fn = 64, center = true, h = 15, r = 7.5000000000);
									cylinder($fn = 64, center = true, h = 15, r = 6.6000000000);
								}
							}
							union() {
								rotate(a = 0.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 20.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 40.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 60.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 80.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 100.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 120.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 140.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 160.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 180.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 200.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 220.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 240.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 260.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 280.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 300.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 320.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
								rotate(a = 340.0000000000) {
									translate(v = [0, 0, 8.5000000000]) {
										translate(v = [0, 0, -2.5000000000]) {
											cube(center = true, size = [13.2000000000, 2.3038346126, 5]);
										}
									}
								}
							}
						}
						translate(v = [0, 0, 2.0000000000]) {
							difference() {
								cylinder($fn = 64, center = true, h = 2, r = 12.4500000000);
								cylinder($fn = 64, center = true, h = 2, r = 6.6000000000);
							}
						}
					}
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
import solid
from make_device import make_unit_array
import os.path as osp
import math

version="v1"
base_path="./designs/plasma_racks/4mm_well_0.5inch_diam_device_"+version+"/"
base_name="12_well_plate_"+version
#basic plate dims
plate_size_outer=[127.5,85.35]
plate_size_inner=[125.5,83.35]
plate_height_outer=8.5
plate_height_inner=8.5
plate_height=plate_height_inner+plate_height_outer
plate_under_depth=1
corner_x=10
corner_y=10
grid_size=[4,3]
dims = [26,26,0]
well_diam=22.9

water_well_diam_out=15
water_well_diam_in=13.2
water_well_height=15
water_well_floor_thickness=2
n_vents = 18
vent_width = math.pi*water_well_diam_in/n_vents
vent_depth = 5


def save_model(model,base_path,base_name):
    if not osp.exists(base_path):
        os.makedirs(base_path)
    scad_path=osp.join(base_path,base_name+".scad")
    solid.scad_render_to_file(model,osp.join(scad_path))

def center_unit_array(model,dims,grid_size):
    model = solid.translate([dims[0]/2.0,dims[1]/2.0,0])(model)
    model = solid.translate([-dims[0]*(grid_size[0]/2.0),
                             -dims[1]*(grid_size[1]/2.0),0])(model)
    return model


#plate_chassis
plate_height_diff=plate_height-plate_height_inner

plate=solid.cube((*plate_size_outer,plate_height_diff),center=True)
plate=solid.translate([0,0,plate_height_diff/2.0])(plate)

plate_inner=solid.cube((*plate_size_inner,plate_height_inner),center=True)
plate_inner=solid.translate([0,0,plate_height_inner/2.0+plate_height_diff])(plate_inner)
plate=solid.union()(plate,plate_inner)

plate_under_remove=solid.cube((*plate_size_inner,plate_under_depth),center=True)
plate_under_remove=solid.translate([0,0,plate_under_depth/2.0])(plate_under_remove)
plate=solid.difference()(plate,plate_under_remove)

#corners
#               0       1        2        3         4          5
corner_points=[[0,0,0],[0,corner_y,10],[0,corner_y,0],[0,corner_y,10],[corner_x,corner_y,10],[corner_x,corner_y,0]]
corner=solid.polygon(points=corner_points)()
corner=solid.linear_extrude(height=plate_height_inner)(corner)

corner_top_left=corner
corner_top_left=solid.translate([0,-corner_y,0])(corner_top_left)
corner_top_left=solid.translate([-plate_size_inner[0]/2.0,plate_size_inner[1]/2.0,plate_height_diff])(corner_top_left)

corner_bottom_left=solid.rotate(90)(corner)
corner_bottom_left=solid.translate([corner_x,0,0])(corner_bottom_left)
corner_bottom_left=solid.translate([-plate_size_inner[0]/2.0,-plate_size_inner[1]/2.0,plate_height_diff])(corner_bottom_left)

corners = solid.union()(corner_top_left,corner_bottom_left)
plate=solid.difference()(plate,corners)

#plate wells
well = solid.cylinder(r=well_diam/2.0, h=plate_height, segments=64, center = True)
well = solid.translate([0,0,plate_height/2.0])(well)
wells=make_unit_array(well,dims,grid_size)
wells=center_unit_array(wells,dims,grid_size)
plate = solid.difference()(plate,wells)

#water wells
water_well_out = solid.cylinder(r=water_well_diam_out/2.0, h=water_well_height, segments=64, center = True)
water_well_in = solid.cylinder(r=water_well_diam_in/2.0, h=water_well_height, segments=64, center = True)
water_well=solid.difference()(water_well_out,water_well_in)
water_well = solid.translate([0,0,water_well_height/2.0+plate_under_depth])(water_well)

vent = solid.cube((water_well_diam_in,vent_width,vent_depth),center=True)
vent = solid.translate([0,0,-vent_depth/2.0])(vent)
vent = solid.translate([0,0,water_well_height/2.0+plate_under_depth])(vent)
vents=[]
for i in range(n_vents):
    rot_vent = solid.rotate(i*360.0/n_vents)(vent)
    vents.append(rot_vent)
vents=solid.union()(*vents)
water_well = solid.difference()(water_well,vents)

water_well_floor_in=solid.cylinder(r=water_well_diam_in/2.0, h=water_well_floor_thickness, segments=64, center = True)
water_well_floor_out=solid.cylinder(r=well_diam/2.0+1, h=water_well_floor_thickness, segments=64, center = True)
water_well_floor=solid.difference()(water_well_floor_out,water_well_floor_in)
water_well_floor=solid.translate([0,0,water_well_floor_thickness/2.0+plate_under_depth])(water_well_floor)
water_well=solid.union()(water_well,water_well_floor)


water_wells=make_unit_array(water_well,dims,grid_size)
water_wells=center_unit_array(water_wells,dims,grid_size)
plate = solid.union()(plate,water_wells)

save_model(plate,base_path,base_name)


 
 
************************************************/
