// Generated by SolidPython 1.1.3 on 2024-01-02 17:03:51


union() {
	translate(v = [-63.5750000000, 42.5250000000, 8.5000000000]) {
		translate(v = [0, -10, 0]) {
			linear_extrude(height = 14) {
				polygon(points = [[0, 0], [0, 10], [0, 10], [0, 10], [10, 10], [10, 10]]);
			}
		}
	}
	translate(v = [-63.5750000000, -42.5250000000, 8.5000000000]) {
		translate(v = [10, 0, 0]) {
			rotate(a = 90) {
				linear_extrude(height = 14) {
					polygon(points = [[0, 0], [0, 10], [0, 10], [0, 10], [10, 10], [10, 10]]);
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
import solid
from make_device import make_unit_array
import os.path as osp

version="v1"
base_path="./designs/plasma_racks/4mm_well_0.5inch_diam_device_"+version+"/"
base_name="12_well_plate_"+version
#basic plate dims
plate_size_outer=[127.5,85.35]
plate_size_inner=[127.15,85.05]
plate_height=22.5
plate_height_inner=14
corner_x=10
corner_y=10
grid_size=[4,3]
dims = [26,26,0]
well_diam=22.9



def save_model(model,base_path,base_name):
    if not osp.exists(base_path):
        os.makedirs(base_path)
    scad_path=osp.join(base_path,base_name+".scad")
    solid.scad_render_to_file(model,osp.join(scad_path))

def center_unit_array(model,dims,grid_size):
    model = solid.translate([dims[0]/2.0,dims[1]/2.0,0])(model)
    model = solid.translate([-dims[0]*(grid_size[0]/2.0),
                             -dims[1]*(grid_size[1]/2.0),0])(model)
    return model


#plate_chassis
plate_height_diff=plate_height-plate_height_inner

plate=solid.cube((*plate_size_outer,plate_height_diff),center=True)
plate=solid.translate([0,0,plate_height_diff/2.0])(plate)

plate_inner=solid.cube((*plate_size_inner,plate_height_inner),center=True)
plate_inner=solid.translate([0,0,plate_height_inner/2.0+plate_height_diff])(plate_inner)
plate=solid.union()(plate,plate_inner)

#corners
#               0       1        2        3         4          5
corner_points=[[0,0,0],[0,corner_y,10],[0,corner_y,0],[0,corner_y,10],[corner_x,corner_y,10],[corner_x,corner_y,0]]
corner=solid.polygon(points=corner_points)()
corner=solid.linear_extrude(height=plate_height_inner)(corner)

corner_top_left=corner
#corner_top_left=solid.translate([-corner_x/2.0,-corner_y/2.0,0])(corner_top_left)
corner_top_left=solid.translate([0,-corner_y,0])(corner_top_left)
corner_top_left=solid.translate([-plate_size_inner[0]/2.0,plate_size_inner[1]/2.0,plate_height_diff])(corner_top_left)

corner_bottom_left=solid.rotate(90)(corner)
corner_bottom_left=solid.translate([corner_x,0,0])(corner_bottom_left)
corner_bottom_left=solid.translate([-plate_size_inner[0]/2.0,-plate_size_inner[1]/2.0,plate_height_diff])(corner_bottom_left)

corners = solid.union()(corner_top_left,corner_bottom_left)
plate=solid.difference()(plate,corners)
save_model(corners,base_path,"corner_test")

well = solid.cylinder(r=well_diam/2.0, h=plate_height, segments=64, center = True)
well = solid.translate([0,0,plate_height/2.0])(well)
wells=make_unit_array(well,dims,grid_size)
wells=center_unit_array(wells,dims,grid_size)
plate = solid.difference()(plate,wells)
save_model(plate,base_path,base_name)
 
 
************************************************/
