// Generated by SolidPython 1.1.3 on 2026-07-06 20:41:48


union() {
	union() {
		translate(v = [-4.5000000000, 36.0000000000, 5.0000000000]) {
			cube(center = true, size = [7, 81, 10]);
		}
		translate(v = [54.0000000000, -4.5000000000, 5.0000000000]) {
			cube(center = true, size = [117, 7, 10]);
		}
		translate(v = [0, 81]) {
			translate(v = [54.0000000000, -4.5000000000, 5.0000000000]) {
				cube(center = true, size = [117, 7, 10]);
			}
		}
		translate(v = [117, 0]) {
			translate(v = [-4.5000000000, 36.0000000000, 5.0000000000]) {
				cube(center = true, size = [7, 81, 10]);
			}
		}
	}
	translate(v = [36.0000000000, 54.0000000000]) {
		difference() {
			cylinder($fn = 256, h = 10, r = 75.0000000000);
			cylinder($fn = 256, h = 10, r = 68.0000000000);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************

"""SCAD file export functions.

This module provides functions for exporting OpenSCAD geometries to .scad files.
"""

from typing import Dict, Optional
from pathlib import Path
import solid

from .config import ExportConfiguration, FileNamingConfig


def export_scad(
    geometry: solid.OpenSCADObject, output_path: Path, header: Optional[str] = None
) -> Path:
    """Export geometry to SCAD file.

    Parameters
    ----------
    geometry : solid.OpenSCADObject
        Geometry to export.
    output_path : Path
        Output file path.
    header : str, optional
        Header comment to add to SCAD file.

    Returns
    -------
    Path
        Path to created SCAD file.

    Raises
    ------
    IOError
        If file cannot be written.

    Examples
    --------
    >>> from pathlib import Path
    >>> import solid
    >>>
    >>> geometry = solid.cube([10, 10, 10])
    >>> output_path = Path('output/device.scad')
    >>> export_scad(geometry, output_path)
    """
    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Render to file
    try:
        solid.scad_render_to_file(geometry, str(output_path))
    except Exception as e:
        raise IOError(f"Failed to write SCAD file to {output_path}: {e}")

    _normalize_scad_file(output_path)

    # Add header if provided
    if header:
        _add_header_to_scad(output_path, header)
        _normalize_scad_file(output_path)

    return output_path


def _normalize_scad_file(scad_path: Path) -> None:
    """Strip trailing whitespace from generated SCAD text."""
    content = scad_path.read_text()
    normalized = "\n".join(line.rstrip() for line in content.splitlines()) + "\n"
    if normalized != content:
        scad_path.write_text(normalized)


def export_multiple_scad(
    geometries: Dict[str, solid.OpenSCADObject],
    config: ExportConfiguration,
    naming_config: Optional[FileNamingConfig] = None,
) -> Dict[str, Path]:
    """Export multiple geometries to SCAD files.

    Parameters
    ----------
    geometries : dict
        Dictionary mapping prefixes to geometries.
        Keys are used as filename prefixes.
    config : ExportConfiguration
        Export configuration.
    naming_config : FileNamingConfig, optional
        File naming configuration.

    Returns
    -------
    dict
        Dictionary mapping prefixes to output paths.

    Examples
    --------
    >>> geometries = {
    ...     'wells': wells_geometry,
    ...     'channels': channels_geometry,
    ...     'device': device_geometry
    ... }
    >>> config = ExportConfiguration(output_directory=Path('output'))
    >>> paths = export_multiple_scad(geometries, config)
    """
    output_paths = {}

    for prefix, geometry in geometries.items():
        # Create naming config for this geometry
        if naming_config:
            file_config = FileNamingConfig(
                prefix=prefix,
                version=naming_config.version,
                grid_size=naming_config.grid_size,
                suffix=naming_config.suffix,
            )
        else:
            file_config = FileNamingConfig(prefix=prefix)

        # Generate filename
        filename = file_config.generate_filename("scad")
        output_path = config.get_output_path(filename)

        # Export
        export_scad(geometry, output_path)
        output_paths[prefix] = output_path

    return output_paths


def _add_header_to_scad(scad_path: Path, header: str):
    """Add header comment to existing SCAD file.

    Parameters
    ----------
    scad_path : Path
        Path to SCAD file.
    header : str
        Header text to add.
    """
    # Read existing content
    with open(scad_path, "r") as f:
        content = f.read()

    # Prepend header
    header_comment = f"// {header}\n\n"
    with open(scad_path, "w") as f:
        f.write(header_comment + content)


def generate_scad_header(
    device_name: str, version: Optional[str] = None, description: Optional[str] = None
) -> str:
    """Generate SCAD file header comment.

    Parameters
    ----------
    device_name : str
        Device name.
    version : str, optional
        Version string.
    description : str, optional
        Device description.

    Returns
    -------
    str
        Header comment text.

    Examples
    --------
    >>> header = generate_scad_header(
    ...     'Two Compartment Device',
    ...     version='v1',
    ...     description='96-well format with microchannels'
    ... )
    """
    lines = []
    lines.append("=" * 60)
    lines.append(f"Device: {device_name}")

    if version:
        lines.append(f"Version: {version}")

    if description:
        lines.append(f"Description: {description}")

    lines.append("Generated by OpenMFD")
    lines.append("=" * 60)

    return "\n".join(lines)


def validate_scad_file(scad_path: Path) -> bool:
    """Validate that SCAD file exists and is readable.

    Parameters
    ----------
    scad_path : Path
        Path to SCAD file.

    Returns
    -------
    bool
        True if file is valid, False otherwise.
    """
    if not scad_path.exists():
        return False

    if not scad_path.is_file():
        return False

    # Try to read file
    try:
        with open(scad_path, "r") as f:
            content = f.read()
        return len(content) > 0
    except Exception:
        return False


************************************************/
