// Generated by SolidPython 0.4.6 on 2020-03-29 23:05:17


union() {
	translate(v = [0.0000000000, 0.0000000000, 0.0000000000]) {
		difference() {
			translate(v = [0, 0]) {
				square(center = true, size = [9.0000000000, 9.0000000000]);
			}
			union() {
				union() {
					translate(v = [-2.2500000000, 2.2500000000]) {
						circle($fn = 64, r = 1.5000000000);
					}
					translate(v = [2.2500000000, 2.2500000000]) {
						circle($fn = 64, r = 1.5000000000);
					}
					translate(v = [-2.2500000000, -2.2500000000]) {
						circle($fn = 64, r = 1.5000000000);
					}
					translate(v = [2.2500000000, -2.2500000000]) {
						circle($fn = 64, r = 1.5000000000);
					}
				}
				union() {
					translate(v = [0, 0.0000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.2400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.2400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.2800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.2800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.3200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.3200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.3600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.3600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.4000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.4000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.4400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.4400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.4800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.4800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.5200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.5200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.5600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.5600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.6000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.6000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.6400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.6400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.6800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.6800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.7200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.7200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.7600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.7600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.8000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.8000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.8400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.8400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.8800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.8800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.9200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.9200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 0.9600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -0.9600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.0000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.0000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.2400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.2400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.2800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.2800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.3200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.3200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.3600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.3600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.4000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.4000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.4400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.4400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.4800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.4800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.5200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.5200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.5600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.5600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.6000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.6000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.6400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.6400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.6800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.6800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.7200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.7200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.7600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.7600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.8000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.8000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.8400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.8400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.8800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.8800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.9200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.9200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 1.9600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -1.9600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.0000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.0000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.0400000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.0800000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.1200000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.1600000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, 2.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
					translate(v = [0, -2.2000000000]) {
						translate(v = [0, 0]) {
							square(center = true, size = [0.8000000000, 0]);
						}
					}
				}
				union() {
					translate(v = [1.3250000000, 0]) {
						square(center = true, size = [1.8500000000, 4.4000000000]);
					}
					translate(v = [-1.3250000000, 0]) {
						square(center = true, size = [1.8500000000, 4.4000000000]);
					}
				}
			}
		}
	}
}